module.exports = {
    content: ["./src/**/*.{html,ts}", "./node_modules/flowbite/**/*.js"],
    darkMode: "class", // or 'media'
    theme: {
        extend: {
            fontFamily: {
                'sans': ['Noto Sans', 'sans-serif'] 
             },
            colors: {
                'dark-bg': '#191716',
                'light-bg': '#ffffff',
                'dark-text': '#EE0258',
                'light-text': '#EE0258',
                'desktop-bg': '#323232',
                pink: {
                    "white": '#E8D5DA',
                    "verylight": '#FFABC2',
                    "light": '#F6668F',
                    DEFAULT: '#EE0258',
                    "dark": '#C40047'
                },
                gray: {
                    "background": '#191716',
                    "component": '#252525',
                    "dark": '#323232',
                    "light": '#454549',
                    "verylight": '#D9D9D9',
                    "lightcomponent": '#9A9A9E',
                },
                default: {
                    DEFAULT: '#EE0258',
                    "text": '#ffffff',
                    "component": '#252525',
                    "dark": '#C40047',
                    "background": '#323232',
                },
                admiration: {
                    DEFAULT: '#D44000',
                    "text": '#FFD700',
                    "component": '#252525',
                    "dark": '#890817',
                    "background": '#5F3625',
                },
                anger:{
                    DEFAULT: '#A40014',
                    "text": '#FFB9B9',
                    "component": '#221113',
                    "dark": '#890817',
                    "background": '#471C21',
                },
                fear:{
                    DEFAULT: '#9A44CE',
                    "text": '#1dff3c',
                    "component": '#C639A2',
                    "dark": '#ff00d8',
                    "background": '#462E5E',
                },
                joy:{
                    DEFAULT: '#FFD700',
                    text: '#FFF8DC',
                    component: '#FFA500',
                    dark: '#FF8C00',
                    background: '#FFFFE0',
                },
                amusement: {
                    DEFAULT: '#FF6347',
                    text: '#FFF5EE',
                    component: '#FF7F50',
                    dark: '#CD5C5C',
                    background: '#FFE4E1',
                },
                annoyance: {
                    DEFAULT: '#FF4500',
                    text: '#FFDAB9',
                    component: '#FF6347',
                    dark: '#CD3700',
                    background: '#FFFAF0',
                },
                approval: {
                    DEFAULT: '#32CD32',
                    text: '#F0FFF0',
                    component: '#3CB371',
                    dark: '#228B22',
                    background: '#E0FFE0',
                },
                caring: {
                    DEFAULT: '#FF69B4',
                    text: '#FFF0F5',
                    component: '#FF1493',
                    dark: '#C71585',
                    background: '#FFD1DC',
                },
                confusion: {
                    DEFAULT: '#8B008B',
                    text: '#E6E6FA',
                    component: '#9932CC',
                    dark: '#4B0082',
                    background: '#DDA0DD',
                },
                curiosity: {
                    DEFAULT: '#FF8C00',
                    text: '#FFF5EE',
                    component: '#FFA500',
                    dark: '#FF7F50',
                    background: '#FFD700',
                },
                desire: {
                    DEFAULT: '#FF69B4',
                    text: '#FFF0F5',
                    component: '#FF1493',
                    dark: '#C71585',
                    background: '#FFE4E1',
                },
                disappointment: {
                    DEFAULT: '#708090',
                    text: '#F5F5F5',
                    component: '#778899',
                    dark: '#2F4F4F',
                    background: '#DCDCDC',
                },
                disapproval: {
                    DEFAULT: '#FF0000',
                    text: '#FFE4E1',
                    component: '#FF6347',
                    dark: '#B22222',
                    background: '#FFC0CB',
                },
                disgust: {
                    DEFAULT: '#556B2F',
                    text: '#F5FFFA',
                    component: '#6B8E23',
                    dark: '#4B5320',
                    background: '#8FBC8F',
                },
                embarrassment: {
                    DEFAULT: '#FFB6C1',
                    text: '#FFF0F5',
                    component: '#FF69B4',
                    dark: '#DB7093',
                    background: '#FFDAB9',
                },
                excitement: {
                    DEFAULT: '#FF4500',
                    text: '#FFD700',
                    component: '#FF6347',
                    dark: '#DC143C',
                    background: '#FFA07A',
                },
                gratitude: {
                    DEFAULT: '#FFD700',
                    text: '#FFF8DC',
                    component: '#FFA500',
                    dark: '#FF8C00',
                    background: '#FFE4B5',
                },
                grief: {
                    DEFAULT: '#2F4F4F',
                    text: '#F5F5F5',
                    component: '#696969',
                    dark: '#1C1C1C',
                    background: '#A9A9A9',
                },
                love: {
                    DEFAULT: '#FF1493',
                    text: '#FFE4E1',
                    component: '#FF69B4',
                    dark: '#C71585',
                    background: '#FFD1DC',
                },
                nervousness: {
                    DEFAULT: '#FF4500',
                    text: '#FFF5EE',
                    component: '#FF6347',
                    dark: '#B22222',
                    background: '#FFE4E1',
                },
                optimism: {
                    DEFAULT: '#FFD700',
                    text: '#FFF8DC',
                    component: '#FFA500',
                    dark: '#FF8C00',
                    background: '#FFFFE0',
                },
                pride: {
                    DEFAULT: '#8A2BE2',
                    text: '#E6E6FA',
                    component: '#9370DB',
                    dark: '#4B0082',
                    background: '#D8BFD8',
                },
                realisation: {
                    DEFAULT: '#00CED1',
                    text: '#E0FFFF',
                    component: '#20B2AA',
                    dark: '#008B8B',
                    background: '#AFEEEE',
                },
                relief: {
                    DEFAULT: '#00FF7F',
                    text: '#F0FFF0',
                    component: '#32CD32',
                    dark: '#228B22',
                    background: '#98FB98',
                },
                remorse: {
                    DEFAULT: '#8B0000',
                    text: '#FFE4E1',
                    component: '#B22222',
                    dark: '#800000',
                    background: '#FA8072',
                },
                sadness: {
                    DEFAULT: '#4682B4',
                    text: '#F0F8FF',
                    component: '#87CEEB',
                    dark: '#4169E1',
                    background: '#B0E0E6',
                },
                surprise: {
                    DEFAULT: '#FF4500',
                    text: '#FFD700',
                    component: '#FF6347',
                    dark: '#FF0000',
                    background: '#FFDAB9',
                },
            }
        },
    },
    variants: {
        extend: {},
    },
    plugins: [require("@tailwindcss/forms"), require("flowbite/plugin")],
};