runtime: nodejs20
instance_class: F2

env: standard

readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

automatic_scaling:
  min_instances: 2
  max_instances: 25
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75

handlers:
  - url: /.*
    script: auto

env_variables:
  NODE_ENV: 'production'
