runtime: nodejs20
instance_class: B1
env: standard

readiness_check:
  path: "/api/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

basic_scaling:
  max_instances: 5
  idle_timeout: 10m

handlers:
  - url: /.*
    script: auto

env_variables:
  NODE_ENV: 'production'