name: linter

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        language: [node, python]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        if: matrix.language == 'node'
        uses: actions/setup-node@v3
        with: 
          node-version: 14

      - name: Install Node.js dependencies
        if: matrix.language == 'node'
        run: npm install

      - name: Run ESLint for Angular/Node.js
        if: matrix.language == 'node'
        run: npx eslint . --ext .ts,.js

      - name: Set up Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies and Run Linter
        if: matrix.language == 'python'
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          flake8 .
