name: linter

on:
    pull_request:
        branches:
            - main
            - develop
    push:
        branches:
            - main
            - develop

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Install Dependencies
              run: npm install

            - name: Check formatting
              run: npx prettier --check **/*.{js,ts}
