on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: run tests
      run: |
        npm install
        cd Backend
        npm run test:cov

    - name: Coveralls
      uses: coverallsapp/github-action@v2
